
[env]
TERM = "xterm-256color"

[window]
opacity = 1.0

[font]
size = 9.0

normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Regular Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
  #"~/.config/alacritty/catppuccin-latte.toml",
]

[terminal]
  
shell = "/usr/bin/zsh"

